version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8089"  # Redirect host port 80 to container port 8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  # Leave empty for no password
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ROOT_PASSWORD: ""  # Set here a password for the root user
      MYSQL_ALLOW_EMPTY_PASSWORD: yes  # If you want to leave the password empty
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    image: oumaimakhelifi/stationski-app-frontend:latest  # Use the version pushed by the pipeline
    ports:
      - "4200:4200"  # Redirect host port 4200 to container port 80
    depends_on:
      - app  # Ensure the backend starts before the frontend

volumes:
  db_data:
