services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"  # Redirige le port 80 du host vers le port 8080 du conteneur
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/stationSki
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: # Laissez vide pour pas de mot de passe
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_USER: root
      MYSQL_PASSWORD: # Laissez vide pour pas de mot de passe
      MYSQL_ROOT_PASSWORD: # Laissez vide pour pas de mot de passe
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
