apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projet-devops-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://192.168.49.2:8443  
  source:
    path: projet-devops-app  
    repoURL: "https://github.com/oumaimakhlifi/projet-DevOps.git"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
