apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projet-devops-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: app/  # Indique la racine du dépôt
    repoURL: "https://github.com/oumaimakhlifi/projet-DevOps.git"
    targetRevision: oumaima  # Utilise la branche 'oumaima'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
