apiVersion: apps/v1
kind: Deployment
metadata:
  name: stationski-frontend
  labels:
    app: stationski-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stationski-frontend
  template:
    metadata:
      labels:
        app: stationski-frontend
    spec:
      containers:
        - name: stationski-frontend
          image: oumaimakhelifi/stationski-app-frontend:latest  # Utiliser la version poussée par le pipeline
          ports:
            - containerPort: 80  # Port exposé à l'intérieur du conteneur
---
apiVersion: v1
kind: Service
metadata:
  name: stationski-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000  # Port pour accéder au frontend depuis l'extérieur
  selector:
    app: stationski-frontend
