apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 80      # Port exposé
      targetPort: 8080  # Port du conteneur
      nodePort: 30080  # Port exposé sur le nœud (facultatif, Minikube choisira un port par défaut si non spécifié)
  type: NodePort  # Utilisez NodePort pour l'exposition locale
