apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: spring-boot-app
spec:
  replicas: 2  # 2 replicas
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: oumaimakhelifi/projet-devops-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://db-service:3306/stationSki?createDatabaseIfNotExist=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""  # Laisser vide pour pas de mot de passe
      restartPolicy: Always
